### ISSUE TITLE
Strange Context For Certain Arguments in Linker

### ISSUE THREAD

**Issue by jgilme1** [knowitall/DocOpenIE#10]
I printed some output to see what was going on with the content collection on linking.

In this example the argument "CDC employees" has 40 sentences as context because the offset of the start of the argument matches the offset of the start of a mention in the mention cluster in two different clusters.

It seems that we should restrict cluster matching to contain the exact offset interval we are seeking that way we don't confuse "CDC employees" with "CDC" or with "CDC employees who are classified..." .

Content Output:
Arg:    10812   CDC employees
Size of extended = 40    // number of sentences added as context to argument

// Cluster output from document

Cluster:
10812   CDC employees who are classified as `` distinguished '' scientists

Cluster:
577 the CDC
843 CDC
1095    the CDC 's
1202    The CDC
1436    CDC
1521    CDC
2459    the CDC 's
2946    CDC
3032    CDC
3855    CDC
4361    CDC
4492    the CDC 's
4904    CDC
5293    The CDC
5541    CDC
6874    CDC
7284    CDC
7366    the CDC 's
7430    the CDC 's
7503    its
7701    CDC
8077    CDC
8222    the CDC
8226    CDC
8412    CDC
9089    CDC 's
9248    these CDC
9362    the CDC
9366    CDC
10329   the CDC 's
10432   the CDC
10812   CDC

**Comment by rbart** [comment]
Linker context collection improved in preq #11
